version: "1"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable:
    - typecheck
    - goimports
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - gofmt
